/**
 * API configuration — all paths use 360coordinates.com
 */

const API_BASE_URL = 'https://360coordinates.com';

export const API_CONFIG = {
  API_BASE_URL,
  BASE_URL: API_BASE_URL,
  UPLOAD_BASE_URL: API_BASE_URL,
  TIMEOUT: 30000,
};

export const API_ENDPOINTS = {
  DEVICE_TOKEN_REGISTER: '/device-token/register',
  DEVICE_TOKEN_UNREGISTER: '/device-token/unregister',
  PROPERTY_SEARCH: '/property/search',
  PROPERTIES_LIST: '/properties',
  PROPERTY_DETAILS: '/property/details',
  PROPERTY_UPDATE: '/property/update',
  PROPERTY_DELETE: '/property/delete',
  MY_PROPERTIES: '/my-properties',
  UPLOAD_IMAGES: '/upload/images',
  SELLER_PROPERTIES_ADD: '/seller/properties/add',
  FAVORITES_LIST: '/favorites',
  FAVORITE_ADD: '/favorite/add',
  FAVORITE_REMOVE: '/favorite/remove',
  FAVORITE_CHECK: '/favorite/check',
  UPLOAD_PROFILE_IMAGE: '/upload/profile-image',
  INQUIRY_SEND: '/inquiry/send',
  SELLER_INQUIRIES_LIST: '/seller/inquiries',
  INQUIRY_INBOX: '/inquiry/inbox',
  INQUIRY_SENT: '/inquiry/sent',
  INQUIRY_MARK_READ: '/inquiry/mark-read',
  INQUIRY_REPLY: '/inquiry/reply',
  MODERATE_AND_UPLOAD: '/moderate-and-upload',
  CHAT_CREATE_ROOM: '/chat/room',
  CHAT_INIT_CONVERSATION: '/chat/init',
  CHAT_MESSAGES: '/chat/messages',
  CHAT_SEND_MESSAGE: '/chat/send',
  BUYER_PROFILE_GET: '/buyer/profile',
  SELLER_PROFILE_GET: '/seller/profile',
  UPDATE_PROFILE: '/profile/update',
  UPLOAD_PICTURE: '/upload/picture',
  CHANGE_PASSWORD: '/change-password',
  OTP_SEND_SMS: '/otp/send-sms',
  OTP_VERIFY_MSG91_TOKEN: '/otp/verify-msg91',
  OTP_VERIFY_SMS: '/otp/verify-sms',
  OTP_SEND_EMAIL: '/otp/send-email',
  OTP_VERIFY_EMAIL: '/otp/verify-email',
  MSG91_OTP_SEND: '/otp/msg91/send',
  MSG91_OTP_VERIFY: '/otp/msg91/verify',
  SELLER_DASHBOARD_STATS: '/seller/dashboard/stats',
  SELLER_PROPERTIES_LIST: '/seller/properties',
  SELLER_BUYERS_GET: '/seller/buyers',
  SELLER_PROFILE_UPDATE: '/seller/profile/update',
  SELLER_INQUIRY_UPDATE_STATUS: '/seller/inquiry/status',
  SELLER_PROPERTIES_DELETE: '/seller/properties/delete',
  SELLER_PROPERTIES_UPDATE: '/seller/properties/update',
  BUYER_PROPERTIES_LIST: '/buyer/properties',
  BUYER_PROPERTY_DETAILS: '/buyer/property/details',
  BUYER_FAVORITES_LIST: '/buyer/favorites',
  BUYER_FAVORITES_TOGGLE: '/buyer/favorites/toggle',
  BUYER_INQUIRY_SEND: '/buyer/inquiry/send',
  BUYER_PROFILE_UPDATE: '/buyer/profile/update',
  BUYER_INTERACTION_RECORD: '/buyer/interaction/record',
  BUYER_INTERACTION_CHECK: '/buyer/interaction/check',
  BUYER_HISTORY_ADD: '/buyer/history/add',
  BUYER_HISTORY_LIST: '/buyer/history',
  REGISTER: '/register',
  LOGIN: '/login',
  VERIFY_OTP: '/verify-otp',
  RESEND_OTP: '/resend-otp',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  REFRESH_TOKEN: '/refresh-token',
  DELETE_ACCOUNT: '/account/delete',
  SWITCH_ROLE: '/switch-role',
  CONTACT_SEND: '/contact/send',
  SELLER_LEADS_LIST: '/seller/leads',
  BUYER_LEAD_CREATE: '/buyer/lead/create',
  MODERATION_CHECK_IMAGE: '/moderation/check-image',
  ADMIN_MODERATION_QUEUE: '/admin/moderation/queue',
  ADMIN_MODERATION_APPROVE: '/admin/moderation/approve',
  ADMIN_MODERATION_REJECT: '/admin/moderation/reject',
};
